PREFIX doc: <https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/Document/3.0/document#>
PREFIX bldg: <https://raw.githubusercontent.com/VCityTeam/UD-Graph/master/Ontologies/CityGML/3.0/building#>
PREFIX owl:    <http://www.w3.org/2002/07/owl#>

SELECT ?subject ?subjectType ?predicate ?object
WHERE {
  ?subject ?predicate ?object;a ?subjectType .
  FILTER (?subjectType IN (doc:Reference, doc:Document, bldg:Building ))
  FILTER(?object != owl:NamedIndividual)
}